import { ConnectButton } from '@rainbow-me/rainbowkit';
import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import { useAccount, useNetwork } from 'wagmi'
import { readContract, writeContract } from '@wagmi/core'
import { abi } from './../utils/abi'
import { useEffect, useState } from 'react';

const Home: NextPage = () => {
  const account = useAccount();
  const { chain } = useNetwork();
  const [balance, setBalance] = useState<any>(0);

  const init = async() => {
    // NFTの残高を取得するメソッド
    const balanceOf = await readContract({ 
      address: '0x1319bE56dBF466EE1200B387194e33893a0E2FF2',
      abi: abi,
      functionName: 'balanceOf',
      args: ['0x034f66d49A175438AD7Ec0111CcA18fce1A39Fa6'],
    })
    console.log("balance", balanceOf)
    setBalance(balanceOf);
  }

  const transfer = async() => {
    writeContract({
      address: '0x1319bE56dBF466EE1200B387194e33893a0E2FF2',
      abi: abi,
      functionName: 'transferFrom',
      args: [account.address, '0xDa6952D4355e11223851EF4BC305D639D4B6A044' ,0],
    })
  };

  useEffect(() => {
    init()
  }, [account])

  return (
    <div className={styles.container}>
      <Head>
        <title>RainbowKit App</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />
        <link href="/favicon.ico" rel="icon" />
      </Head>

      <main className={styles.main}>
        <ConnectButton />

        <h1 className={styles.title}>
          Welcome to <a href="">RainbowKit</a> + <a href="">wagmi</a> +{' '}
          <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.tsx</code>
        </p>

        <div className={styles.grid}>
          <a className={styles.card} href="https://rainbowkit.com">
            <h2>ChainID: {chain?.id}</h2>
          </a>

          <a className={styles.card} href="https://rainbowkit.com">
            <h2>Status: {account.status}</h2>
          </a>

          <a className={styles.card} href="https://wagmi.sh">
            <h2>balance: {balance}</h2>
          </a>

          <a
            className={styles.card}
            href="https://github.com/rainbow-me/rainbowkit/tree/main/examples"
          >
            <button
              onClick={async() => await transfer()}
            >
              <h2>RainbowKit Examples &rarr;</h2>
            </button>
          </a>

          <a className={styles.card} href="https://nextjs.org/docs">
            <h2>Next.js Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a
            className={styles.card}
            href="https://github.com/vercel/next.js/tree/canary/examples"
          >
            <h2>Next.js Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            className={styles.card}
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a href="https://rainbow.me" rel="noopener noreferrer" target="_blank">
          Made with ❤️ by your frens at 🌈
        </a>
      </footer>
    </div>
  );
};

export default Home;
